[package]
name = "diskspace_insight"
version = "0.1.3"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Investigate where your diskspace has gone"
keywords = ["disk", "utility", "diskspace"]
repository = "https://github.com/woelper/diskspace-insight"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5.1"
rayon = "1.4.1"
log = "0.4.11"
env_logger = "0.7.1"
bytesize = "1.0.1"